### ISSUE TITLE
Idea: allow sloppy validation

### ISSUE THREAD

**Issue by metachris** [flashbots/mev-boost-relay#394]
The builder submission validation logic was fixed in https://github.com/flashbots/mev-boost-relay/pull/379, which tripled the number of block validations again.

This proposal is for allowing relays to have an optional "sloppy" validation mode, which would reduce the number of validations to ~1/3rd, with the possible downside of producing lower overall value top bids in certain cases.

The sloppy validation mode would work like before, skipping any non-cancellable bid below the current top bid value (rather than this builders latest value).

Example:
1. builder A submits bid of 1 ETH (cancellable)
2. builder B submits bid of 0.9 ETH (non-cancellable, would be dismissed)
3. builder A cancels his 1 ETH bid by submitting a 0.5 ETH bid

In the current code, the top bid is 0.9ETH, whereas with sloppy validation the 0.9ETH bid would have been skipped and the top bid being only 0.5 ETH.

---

Any thoughts or opinions? Seems reasonable to let relays decide this for themselves?

**Comment by michaelneuder** [comment]
i think this is pretty bad actually. because now builders will use shielding bids with much more effect: https://ethresear.ch/t/bid-cancellations-considered-harmful/15500#bid-shielding-9.

bid shielding now has the added benefit of totally blocking all lower bids. i think if we wanted to do this, we should save whether or not a bid is "cancellable". we could then cancel a bid only if the existing highest bid *and* the new incoming bid have cancellations enabled. but this would require some db/redis changes, which im not sure are worth the technical complexity.

**Comment by metachris** [comment]
Ooh you're of course totally right, my bad 😂  I recall we recently talked about it too.
