### ISSUE TITLE
[code health] remove bellatrix logic from relay

### ISSUE THREAD

**Issue by michaelneuder** [flashbots/mev-boost-relay#430]
now that we are safely post-capella hard-fork, a good clean up task is removing the bellatrix code. i plan on doing two steps.

1. remove from service.go critical path. 
2. remove all extraneous types and references.

splitting these two up should make the rollback path easier in case there is any issue rolling out and running (1).

**Comment by metachris** [comment]
That's a good idea, also to split up into two steps.

Keep in mind that we'll need _somewhat_ similar logic for upcoming 4844 types, not sure there is structure we want to keep in place for that. Otherwise we can just reintroduce when it's time for it.

For reference, removing the Bellatrix types has been discussed in Eth R&D Discord, and been widely agreed on
<img width="1311" alt="Screenshot 2023-04-23 at 23 24 12" src="https://github.com/flashbots/mev-boost-relay/assets/116939/d1c4819d-255e-4511-973c-971a2be17b8f">
